const Info = [
  {
    image: "zaferes.png",
    info: "Zaferes is very good Instructor",
    state: "USA",
    price: 66,
    reviews: 4,
    rating: 4.5,
  },
  {
    image: "guitar.png",
    info: "Guitar Guide really nice",
    state: "N/A",
    price: 120,
    reviews: 200,
    rating: 4,
  },
  {
    image: "zaferes.png",
    info: "Zaferes is very good Instructor",
    state: "USA",
    price: 66,
    reviews: 4,
    rating: 4.5,
  },
  {
    image: "guitar.png",
    info: "Guitar Guide really nice",
    state: "N/A",
    price: 120,
    reviews: 200,
    rating: 4,
  },
  {
    image: "zaferes.png",
    info: "Zaferes is very good Instructor",
    state: "USA",
    price: 66,
    reviews: 4,
    rating: 4.5,
  },
  {
    image: "guitar.png",
    info: "Guitar Guide really nice",
    state: "N/A",
    price: 120,
    reviews: 200,
    rating: 4,
  },
  {
    image: "zaferes.png",
    info: "Zaferes is very good Instructor",
    state: "USA",
    price: 66,
    reviews: 4,
    rating: 4.5,
  },
  {
    image: "guitar.png",
    info: "Guitar Guide really nice",
    state: "N/A",
    price: 120,
    reviews: 200,
    rating: 4,
  },
];

export default Info;
